#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "VS Code & Open VSX Publishing Setup (Sonar Agent)"

# ── Stage 1: Marketplace Publisher Verification ───────────────────────────
stage "Marketplace: Publisher Verification"
say "We need to verify that your VS Code Marketplace publisher matches package.json ('chulit')."
open_url "https://marketplace.visualstudio.com/manage"
step "Log in with your Microsoft account if prompted."
step "Check if you have a publisher with ID 'chulit'. If not, click 'Create publisher' with ID: chulit."
ask VSCE_PUBLISHER "Enter your VS Code Marketplace Publisher ID [default: chulit]:"
VSCE_PUBLISHER="${VSCE_PUBLISHER:-chulit}"
write_env VSCE_PUBLISHER "$VSCE_PUBLISHER"

# ── Stage 2: Azure DevOps Personal Access Token (PAT) ────────────────────
stage "Azure DevOps: Personal Access Token (PAT)"
say "VSCE requires a Personal Access Token (PAT) from Azure DevOps with Marketplace scope."
open_url "https://dev.azure.com/"
step "Click on 'User settings' (icon near top-right profile photo) → 'Personal access tokens'."
step "Click '+ New Token'."
step "Set Organization to: 'All accessible organizations' (CRITICAL: single org will fail!)."
step "Set Expiration as desired (e.g. 90 or 365 days)."
step "Under Scopes, click 'Show all scopes' or 'Custom defined', find 'Marketplace', and check 'Manage'."
step "Click 'Create' and copy the generated token immediately."
ask_secret VSCE_PAT "Paste your Azure DevOps PAT (VSCE_PAT):"
write_env VSCE_PAT "$VSCE_PAT"

# ── Stage 3: Open VSX Access Token ───────────────────────────────────────
stage "Open VSX: Account & Access Token"
say "Open VSX (open-vsx.org) is the open-source registry used by VSCodium, Cursor, Gitpod, etc."
open_url "https://open-vsx.org/"
step "Log in using GitHub or Eclipse account."
step "Go to your Profile / Settings → 'Access Tokens'."
step "Click 'Generate New Token' (Name: e.g. sonar-agent)."
step "Copy the token."
note "Note: Ensure you have claimed or created namespace 'chulit' on Open VSX (matching publisher name)."
ask_secret OVSX_PAT "Paste your Open VSX Access Token (OVSX_PAT):"
if [[ -n "$OVSX_PAT" ]]; then
  write_env OVSX_PAT "$OVSX_PAT"
  step "Ensuring namespace 'chulit' exists on Open VSX..."
  npx ovsx create-namespace chulit -p "$OVSX_PAT" || true
fi

# ── Stage 4: Local Packaging & Build Verification ────────────────────────
stage "Package Verification: Build & Bundle"
say "We will test-build and package the extension locally to ensure there are no bundling or manifest errors."
if confirm "Run 'npm run build' and 'npm run package' now?"; then
  printf '\n'
  npm run build
  npm run package
  printf '\n'
  step "Package verified! .vsix bundle generated successfully."
  pause "Press Enter to proceed to publish options."
else
  note "Skipped packaging step."
fi

# ── Stage 5: Direct Publish ──────────────────────────────────────────────
stage "Marketplace & Open VSX: Direct Publish"
say "You can publish the extension directly now via CLI."
if [[ -n "$VSCE_PAT" ]] && confirm "Publish to Visual Studio Marketplace now?"; then
  printf '\n'
  npx @vscode/vsce publish -p "$VSCE_PAT"
  printf '\n'
  say "Published successfully to Visual Studio Marketplace!"
fi

if [[ -n "${OVSX_PAT:-}" ]] && confirm "Publish to Open VSX Registry now?"; then
  printf '\n'
  npx ovsx publish -p "$OVSX_PAT"
  printf '\n'
  say "Published successfully to Open VSX!"
fi
pause "Press Enter to proceed to CI/CD setup."

# ── Stage 6: GitHub Actions CI/CD Secrets Setup ──────────────────────────
stage "GitHub Actions: Automated Release Secrets"
say "Configure VSCE_PAT and OVSX_PAT in GitHub repo secrets so GitHub Actions auto-publishes both on push to 'main'."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  [[ -n "$VSCE_PAT" ]] && set_secret VSCE_PAT "$VSCE_PAT"
  [[ -n "${OVSX_PAT:-}" ]] && set_secret OVSX_PAT "$OVSX_PAT"
else
  open_url "https://github.com/chulit/sonar-agent/settings/secrets/actions"
  step "Click 'New repository secret'."
  step "Secret 1: Name = 'VSCE_PAT', Value = Azure DevOps PAT."
  if [[ -n "${OVSX_PAT:-}" ]]; then
    step "Secret 2: Name = 'OVSX_PAT', Value = Open VSX Token."
  fi
  pause "Done adding secret(s) on GitHub? Press Enter to finish."
fi

# ──────────────────────────────────────────────────────────────────────────

finish

